name: Restart Codespace

on:
  schedule:
    
cron: "0 /4 * *" # Runs every 4 hours

jobs:
  restart-codespace:
    runs-on: ubuntu-latest

    steps:
      
name: Checkout repository
      uses: actions/checkout@v3

      
name: Install GitHub CLI
      run: sudo apt-get install gh

      
name: Restart Codespace
      run: |
        gh codespace stop <upgraded-meme-jjjvxrvq4q763j667>
        gh codespace start <upgraded-meme-jjjvxrvq4q763j667>
